### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by eckelj** [planetmint/benchmark#6]

**Comment by eckelj** [comment]
exit the benchmark script after 
--time mode is timed out so that all processes and threads are terminating
--requests are processed so that all processes and threads are terminating
assumption: this should happen via exit(0)

**Comment by liviu-lesan** [comment]
https://github.com/planetmint/benchmark/commit/912e174a08815bc9ffb510c3ba0ad753b964c2c9

**Comment by eckelj** [comment]
@liviu-lesan have look: 
running this command
`planetmint-benchmark --csv out.csv --processes=10 --peer http://3.70.186.190:9984 send -qs 100 --size 10 -r 130 `
does not result in getting the process terminated
