### ISSUE TITLE
tow modes: --time and --requests

### ISSUE THREAD

**Issue by eckelj** [planetmint/benchmark#7]
if time is defined as a duration, we do not need to respect and define requests. and will continusly generate new messages, so that the queue is always full.

**Comment by liviu-lesan** [comment]
https://github.com/planetmint/benchmark/commit/912e174a08815bc9ffb510c3ba0ad753b964c2c9

**Comment by eckelj** [comment]
@liviu-lesan 
`planetmint-benchmark --csv out.csv --processes=10 --peer http://3.70.186.190:9984 send -qs 100 --size 10 --time 2`
should enter the --time mode. However, only one intial request package is created and it dos not create new TX to be submitted.
